const ALTERNATIVEWORDS = [
  "uintathere",
  "uintatherium",
  "ukrayina",
  "ulanova",
  "ultracef",
  "ulvophyceae",
  "umbellales",
  "umbrellalike",
  "umbundu",
  "unabused",
  "unadvisedly",
  "unaffectedness",
  "unalarming",
  "unalert",
  "unannealed",
  "unapprehensive",
  "unarbitrary",
  "unattired",
  "unau",
  "unbaffled",
  "unbigoted",
  "unbitter",
  "unblushing",
  "unbodied",
];
module.exports = ALTERNATIVEWORDS;
