const soft404s = [
  "/define/ahed",
  "/define/arilloid",
  "/define/admixt",
  "/define/abomasi",
  "/define/automen",
  "/define/airworthier",
  "/define/ybit",
  "/define/acridest",
  "/define/aureolae",
  "/define/automobiled",
  "/define/ansae",
  "/define/agiler",
  "/define/awkwarder",
  "/define/arcked",
  "/define/kaury",
  "/define/auldest",
  "/define/anenst",
  "/define/cementite",
  "/define/aridest",
  "/define/askoi",
  "/define/alphabetiser",
  "/define/auntlier",
  "/define/atok",
  "/define/aceta",
  "/define/airworthiest",
  "/define/ahing",
  "/define/audibilized",
  "/define/abought",
  "/define/apteria",
  "/define/adepter",
  "/define/attritting",
  "/define/andantini",
  "/define/abollae",
  "/define/arider",
  "/define/bibliotist",
  "/define/angstiest",
  "/define/alhacen",
  "/define/ahind",
  "/define/anestri",
  "/define/aiyee",
  "/define/ailanthic",
];

// Export the string array using module.exports
module.exports = soft404s;