"use client";
import WordFilter from "./WordFilter";

const words = [
  "zoological garden",
  "zoological science",
  "zoologist",
  "zoology",
  "zoom",
  "zoom along",
  "zoom in",
  "zoom lens",
  "zoomastigina",
  "zoomastigote",
  "zoomorphism",
  "zoonosis",
  "zoonotic",
  "zoonotic disease",
  "zoophagous",
  "zoophilia",
  "zoophilism",
  "zoophobia",
  "zoophyte",
  "zooplankton",
  "zoopsia",
  "zoospore",
  "zoot suit",
  "zootoxin",
  "zori",
  "zoril",
  "zoroaster",
  "zoroastrian",
  "zoroastrianism",
  "zoster",
  "zostera",
  "zostera marina",
  "zosteraceae",
  "zovirax",
  "zoysia",
  "zoysia japonica",
  "zoysia matrella",
  "zoysia tenuifolia",
  "zr",
  "zsigmondy",
  "zu",
  "zubird",
  "zucchini",
  "zuider zee",
  "zukerman",
  "zulu",
  "zumbooruck",
  "zumbooruk",
  "zuni",
  "zurich",
  "zurvan",
  "zurvanism",
  "zweig",
  "zwieback",
  "zwingli",
  "zworykin",
  "zydeco",
  "zygnema",
  "zygnemales",
  "zygnemataceae",
  "zygnematales",
  "zygocactus",
  "zygocactus truncatus",
  "zygodactyl",
  "zygodactyl foot",
  "zygoma",
  "zygomatic",
  "zygomatic arch",
  "zygomatic bone",
  "zygomatic process",
  "zygomorphic",
  "zygomorphous",
  "zygomycetes",
  "zygomycota",
  "zygomycotina",
  "zygophyllaceae",
  "zygophyllum",
  "zygophyllum fabago",
  "zygoptera",
  "zygospore",
  "zygote",
  "zygotene",
  "zygotic",
  "zyloprim",
  "zymase",
  "zymogen",
  "zymoid",
  "zymology",
  "zymolysis",
  "zymolytic",
  "zymosis",
  "zymotic",
  "zymurgy",
  "zyrian",
];

export default function MyPage() {
  return (
    <div>
      <h1>Filter Words</h1>
      <WordFilter words={words} />
    </div>
  );
}
