// constants.js
// 1. ARENA CONFIGURATION
// We use "Atmospheric" backgrounds (Zinc/Slate) so the Rank colors pop.
export const ARENAS = {
  1: {
    id: 1,
    name: "The Inner Seed",
    arenaBg: "bg-zinc-50 dark:bg-zinc-900",
    description: "The beginning of sound.",
  },
  2: {
    id: 2,
    name: "The Mother's Lap",
    arenaBg: "bg-stone-50 dark:bg-stone-900",
    description: "Domestic comfort and warmth.",
  },
  3: {
    id: 3,
    name: "The Tulsi Courtyard",
    arenaBg: "bg-slate-50 dark:bg-slate-900",
    description: "Nature within the household.",
  },
  4: {
    id: 4,
    name: "The Village Gurukul",
    arenaBg: "bg-zinc-100 dark:bg-zinc-900",
    description: "Learning in the community.",
  },
  5: {
    id: 5,
    name: "The Temple Square",
    arenaBg: "bg-stone-100 dark:bg-stone-900",
    description: "Social and spiritual connection.",
  },
  6: {
    id: 6,
    name: "The Forest Path",
    arenaBg: "bg-zinc-50 dark:bg-zinc-950",
    description: "Venturing into the wild unknown.",
  },
  7: {
    id: 7,
    name: "The Royal Court",
    arenaBg: "bg-slate-100 dark:bg-zinc-950",
    description: "Governance and honor.",
  },
  8: {
    id: 8,
    name: "The Great River",
    arenaBg: "bg-blue-50/30 dark:bg-zinc-950",
    description: "World's wisdom.",
  },
  9: {
    id: 9,
    name: "The Solar Chariot",
    arenaBg: "bg-orange-50/20 dark:bg-zinc-950",
    description: "Cosmic light.",
  },
  10: {
    id: 10,
    name: "The Cosmic Dance",
    arenaBg: "bg-zinc-950",
    description: "Unity with the infinite.",
  },
};

// 2. RANK CONFIGURATION
// These colors now drive EVERY accent in the game (Balloons, Buttons, Overlays)
export const RANKS = [
  {
    level: 1,
    name: "Infant",
    arenaId: 1,
    minXP: 0,
    maxTries: 10,
    color: "#75c32c", // Original Green (Starting Point)
    stageName: ARENAS[1].name,
  },
  {
    level: 2,
    name: "Toddler",
    arenaId: 2,
    minXP: 500,
    maxTries: 10,
    color: "#059669", // Emerald (Healthy growth)
    stageName: ARENAS[2].name,
  },
  {
    level: 3,
    name: "Student",
    arenaId: 3,
    minXP: 1500,
    maxTries: 9,
    color: "#0284c7", // Sky Blue (Learning/Clear mind)
    stageName: ARENAS[3].name,
  },
  {
    level: 4,
    name: "Scholar",
    arenaId: 4,
    minXP: 3500,
    maxTries: 8,
    color: "#2563eb", // Royal Blue (Knowledge/Stability)
    stageName: ARENAS[4].name,
  },
  {
    level: 5,
    name: "Sage",
    arenaId: 5,
    minXP: 8000,
    maxTries: 8,
    color: "#4f46e5", // Indigo (Deep focus/Wisdom)
    stageName: ARENAS[5].name,
  },
  {
    level: 6,
    name: "Yogi",
    arenaId: 6,
    minXP: 18000,
    maxTries: 7,
    color: "#7c3aed", // Violet (Spiritual balance)
    stageName: ARENAS[6].name,
  },
  {
    level: 7,
    name: "Guru",
    arenaId: 7,
    minXP: 37000,
    maxTries: 7,
    color: "#c026d3", // Fuchsia (Vibrancy/Influence)
    stageName: ARENAS[7].name,
  },
  {
    level: 8,
    name: "Master",
    arenaId: 8,
    minXP: 75000,
    maxTries: 6,
    color: "#db2777", // Pink/Rose (Intensity/Skill)
    stageName: ARENAS[8].name,
  },
  {
    level: 9,
    name: "Legend",
    arenaId: 9,
    minXP: 125000,
    maxTries: 6,
    color: "#ea580c", // Deep Orange (Legendary Fire)
    stageName: ARENAS[9].name,
  },
  {
    level: 10,
    name: "Word Papa",
    arenaId: 10,
    minXP: 210000,
    maxTries: 5,
    color: "#dc2626", // Red (The Ultimate Rank/Highest Difficulty)
    stageName: ARENAS[10].name,
  },
];

// Test Ranks (for testing rank up mechanics without needing to earn tons of XP)
// export const RANKS = [
//   {
//     level: 1,
//     name: "Infant",
//     arenaId: 1,
//     minXP: 0,
//     maxTries: 10,
//     color: "#75c32c", // Original Green (Starting Point)
//     stageName: ARENAS[1].name,
//   },
//   {
//     level: 2,
//     name: "Toddler",
//     arenaId: 2,
//     minXP: 100,
//     maxTries: 10,
//     color: "#059669", // Emerald (Healthy growth)
//     stageName: ARENAS[2].name,
//   },
//   {
//     level: 3,
//     name: "Student",
//     arenaId: 3,
//     minXP: 250,
//     maxTries: 9,
//     color: "#0284c7", // Sky Blue (Learning/Clear mind)
//     stageName: ARENAS[3].name,
//   },
//   {
//     level: 4,
//     name: "Scholar",
//     arenaId: 4,
//     minXP: 700,
//     maxTries: 8,
//     color: "#2563eb", // Royal Blue (Knowledge/Stability)
//     stageName: ARENAS[4].name,
//   },
//   {
//     level: 5,
//     name: "Sage",
//     arenaId: 5,
//     minXP: 1500,
//     maxTries: 8,
//     color: "#4f46e5", // Indigo (Deep focus/Wisdom)
//     stageName: ARENAS[5].name,
//   },
//   {
//     level: 6,
//     name: "Yogi",
//     arenaId: 6,
//     minXP: 2500,
//     maxTries: 7,
//     color: "#7c3aed", // Violet (Spiritual balance)
//     stageName: ARENAS[6].name,
//   },
//   {
//     level: 7,
//     name: "Guru",
//     arenaId: 7,
//     minXP: 3700,
//     maxTries: 7,
//     color: "#c026d3", // Fuchsia (Vibrancy/Influence)
//     stageName: ARENAS[7].name,
//   },
//   {
//     level: 8,
//     name: "Master",
//     arenaId: 8,
//     minXP: 5000,
//     maxTries: 6,
//     color: "#db2777", // Pink/Rose (Intensity/Skill)
//     stageName: ARENAS[8].name,
//   },
//   {
//     level: 9,
//     name: "Legend",
//     arenaId: 9,
//     minXP: 7000,
//     maxTries: 6,
//     color: "#ea580c", // Deep Orange (Legendary Fire)
//     stageName: ARENAS[9].name,
//   },
//   {
//     level: 10,
//     name: "Word Papa",
//     arenaId: 10,
//     minXP: 10000,
//     maxTries: 5,
//     color: "#dc2626", // Red (The Ultimate Rank/Highest Difficulty)
//     stageName: ARENAS[10].name,
//   },
// ];


// 3. WORDS POOL (15 words per stage)
export const WORDS_POOL = {
  1: [
    { word: "SUN", category: "Nature", hint: "Big yellow ball in the sky" },
    { word: "SKY", category: "Nature", hint: "Blue space above us" },
    { word: "MUD", category: "Nature", hint: "Wet dirt after rain" },
    { word: "ONE", category: "Number", hint: "The number after zero" },
    { word: "AIR", category: "Nature", hint: "What you breathe" },
    { word: "DAY", category: "Time", hint: "When it is light outside" },
    { word: "CAT", category: "Animal", hint: "A pet that says meow" },
    { word: "SON", category: "Family", hint: "A male child" },
    { word: "EAR", category: "Body", hint: "You use this to hear" },
    { word: "EAT", category: "Action", hint: "To put food in your mouth" },
    { word: "RUN", category: "Action", hint: "To move quickly on feet" },
    { word: "SIT", category: "Action", hint: "To rest on a chair" },
    { word: "BIG", category: "Adj", hint: "Opposite of small" },
    { word: "RED", category: "Color", hint: "Color of an apple" },
    { word: "DOG", category: "Animal", hint: "A pet that barks" },
    { word: "TWO", category: "Number", hint: "Comes after one" },
    { word: "MOON", category: "Nature", hint: "Shines at night" },
    { word: "SEA", category: "Nature", hint: "Large salt water body" },
    { word: "MAN", category: "Family", hint: "An adult male" },
    { word: "MOM", category: "Family", hint: "Another word for mother" },
    { word: "LEG", category: "Body", hint: "Used to walk" },
    { word: "EYE", category: "Body", hint: "You use this to see" },
    { word: "HAT", category: "Object", hint: "Worn on the head" },
    { word: "CAR", category: "Object", hint: "Vehicle with four wheels" },
    { word: "BED", category: "Object", hint: "You sleep on this" },
    { word: "TOY", category: "Object", hint: "Children play with it" },
    { word: "FAN", category: "Object", hint: "Blows air to cool you" },
    { word: "ICE", category: "Nature", hint: "Frozen water" },
    { word: "COW", category: "Animal", hint: "Gives milk" },
    { word: "PIG", category: "Animal", hint: "Farm animal that oinks" },
    { word: "BAT", category: "Animal", hint: "Flying mammal at night" },
    { word: "ANT", category: "Animal", hint: "Tiny insect that crawls" },
    { word: "TEN", category: "Number", hint: "Comes after nine" },
    { word: "HOT", category: "Adj", hint: "Opposite of cold" },
    { word: "WET", category: "Adj", hint: "Opposite of dry" },
    { word: "BOX", category: "Object", hint: "You can put things inside" },
    { word: "PAN", category: "Object", hint: "Used for cooking" },
    { word: "PEN", category: "Object", hint: "You write with this" },
    { word: "MAP", category: "Object", hint: "Shows places and roads" },
    { word: "BEE", category: "Animal", hint: "Makes honey" },
    { word: "HEN", category: "Animal", hint: "Bird that lays eggs" },
    { word: "RAT", category: "Animal", hint: "Looks like a big mouse" },
    { word: "ZIP", category: "Object", hint: "Closes clothes or bags" },
    { word: "TOP", category: "Object", hint: "The highest part" },
    { word: "CUP", category: "Object", hint: "You drink from this" },
    { word: "FUN", category: "Adj", hint: "Something that makes you happy" },
  ],
  2: [
    { word: "MILK", category: "Food", hint: "Often poured on cereal" },
    {
      word: "BOWL",
      category: "Home",
      hint: "Round container for holding things",
    },
    {
      word: "LOVE",
      category: "Emotion",
      hint: "What hearts usually stand for",
    },
    {
      word: "HOME",
      category: "Place",
      hint: "Where you return after being away",
    },
    { word: "PRAY", category: "Action", hint: "Done quietly with closed eyes" },
    { word: "KIND", category: "Adj", hint: "Opposite of mean" },
    { word: "BABY", category: "Family", hint: "Sleeps a lot and cries often" },
    { word: "HAND", category: "Body", hint: "Used to wave or hold things" },
    { word: "FOOD", category: "Home", hint: "Needed for energy each day" },
    { word: "STAR", category: "Nature", hint: "Shines far away at night" },
    { word: "SOFT", category: "Adj", hint: "Not hard when you touch it" },
    {
      word: "PLAY",
      category: "Action",
      hint: "Children spend time doing this",
    },
    { word: "SING", category: "Action", hint: "Done with rhythm and melody" },
    { word: "GIVE", category: "Action", hint: "Opposite of keep" },
    { word: "BOOK", category: "Object", hint: "Has pages you can turn" },
    { word: "CHAIR", category: "Home", hint: "Something you sit on" },
    { word: "WALL", category: "Home", hint: "Keeps rooms apart" },
    { word: "RICE", category: "Food", hint: "Tiny grains cooked for meals" },
    { word: "CAKE", category: "Food", hint: "Often eaten at birthdays" },
    { word: "TEA", category: "Food", hint: "Hot drink made with leaves" },
    { word: "FISH", category: "Animal", hint: "Lives in water and swims" },
    { word: "BIRD", category: "Animal", hint: "Has wings and can fly" },
    { word: "TREE", category: "Nature", hint: "Has roots, trunk, and leaves" },
    { word: "RAIN", category: "Nature", hint: "Falls from clouds" },
    { word: "SNOW", category: "Nature", hint: "Cold flakes from the sky" },
    { word: "WIND", category: "Nature", hint: "Moves leaves and kites" },
    { word: "FIRE", category: "Nature", hint: "Gives heat and light" },
    { word: "CUP", category: "Home", hint: "Used for drinking" },
    { word: "DOOR", category: "Home", hint: "You open it to enter" },
    { word: "KEY", category: "Object", hint: "Used to unlock things" },
    { word: "BAG", category: "Object", hint: "Carries your belongings" },
    { word: "BOX", category: "Object", hint: "Keeps things inside" },
    { word: "DOLL", category: "Object", hint: "Looks like a small person" },
    { word: "BALL", category: "Object", hint: "Round and used in games" },
    { word: "HAT", category: "Object", hint: "Worn on the head" },
    { word: "SHOE", category: "Object", hint: "Covers your foot" },
    { word: "SOAP", category: "Home", hint: "Used with water to clean" },
    { word: "CLOCK", category: "Home", hint: "Tells the time" },
    { word: "ROAD", category: "Place", hint: "Cars move along it" },
    { word: "CITY", category: "Place", hint: "Has many buildings and people" },
    { word: "PARK", category: "Place", hint: "Open area with grass and trees" },
    { word: "SHOP", category: "Place", hint: "Where you buy things" },
    { word: "SCHOOL", category: "Place", hint: "Children go here to learn" },
    { word: "WORK", category: "Action", hint: "Adults spend time doing this" },
    { word: "READ", category: "Action", hint: "Done with books or papers" },
    { word: "WRITE", category: "Action", hint: "Done with a pen or pencil" },
    { word: "DRAW", category: "Action", hint: "Making pictures on paper" },
    { word: "JUMP", category: "Action", hint: "Both feet leave the ground" },
  ],
  3: [
    { word: "GARDEN", category: "Place", hint: "Where flowers grow" },
    { word: "FLOWER", category: "Nature", hint: "Colorful part of a plant" },
    { word: "FRUIT", category: "Food", hint: "Sweet food like mango or apple" },
    { word: "PLANT", category: "Nature", hint: "Grows from a seed in soil" },
    { word: "WATER", category: "Nature", hint: "You drink it when thirsty" },
    { word: "GREEN", category: "Color", hint: "Color of most leaves" },
    { word: "SMALL", category: "Adj", hint: "Not taking up much space" },
    { word: "BIRD", category: "Animal", hint: "Has wings and can fly" },
    { word: "SWEET", category: "Food", hint: "Tastes like sugar or honey" },
    { word: "SHADE", category: "Nature", hint: "Cool area away from the sun" },
    { word: "TULSI", category: "Sacred", hint: "Holy basil plant" },
    { word: "LEAF", category: "Nature", hint: "Green part of a branch" },
    { word: "SMILE", category: "Emotion", hint: "A happy look on your face" },
    { word: "ROOTS", category: "Nature", hint: "Part of a plant under ground" },
    { word: "CLEAN", category: "Adj", hint: "Free from dirt or marks" },
    { word: "SUN", category: "Nature", hint: "It shines in the sky" },
    { word: "MOON", category: "Nature", hint: "It glows at night" },
    { word: "STAR", category: "Nature", hint: "Tiny lights in the sky" },
    { word: "TREE", category: "Nature", hint: "Tall plant with branches" },
    { word: "COW", category: "Animal", hint: "Gives us milk" },
    { word: "MILK", category: "Food", hint: "White drink from cows" },
    { word: "HAPPY", category: "Emotion", hint: "Feeling good and cheerful" },
    { word: "PLAY", category: "Action", hint: "What children love to do" },
    { word: "HOME", category: "Place", hint: "Where you live" },
    { word: "ROAD", category: "Place", hint: "Cars move on it" },
    { word: "SUNSET", category: "Nature", hint: "When the sun goes down" },
    { word: "RAIN", category: "Nature", hint: "Water falling from clouds" },
    { word: "CLOUD", category: "Nature", hint: "White shapes in the sky" },
    { word: "FISH", category: "Animal", hint: "Lives in water" },
    { word: "CAT", category: "Animal", hint: "A pet that meows" },
    { word: "DOG", category: "Animal", hint: "A pet that barks" },
    { word: "MILKY", category: "Adj", hint: "Looks like milk" },
    { word: "HILL", category: "Place", hint: "Smaller than a mountain" },
    { word: "TOY", category: "Item", hint: "Children play with it" },
    { word: "LIGHT", category: "Nature", hint: "Helps you see" },
    { word: "DAY", category: "Time", hint: "When the sun is up" },
    { word: "NIGHT", category: "Time", hint: "When the moon shines" },
    { word: "PATH", category: "Place", hint: "A small way to walk" },
    { word: "CUP", category: "Item", hint: "You drink tea in it" },
    { word: "CHAIR", category: "Item", hint: "You sit on it" },
    { word: "TABLE", category: "Item", hint: "You eat food on it" },
    { word: "FOOD", category: "Item", hint: "What you eat" },
    { word: "JUICE", category: "Food", hint: "Drink made from fruits" },
    { word: "BREAD", category: "Food", hint: "Made from flour" },
    { word: "RICE", category: "Food", hint: "White grains we eat" },
    { word: "SUNRISE", category: "Nature", hint: "When the sun comes up" },
    { word: "COLD", category: "Adj", hint: "Opposite of hot" },
  ],
  4: [
    { word: "SCHOOL", category: "Place", hint: "Building for education" },
    { word: "LEARN", category: "Action", hint: "To gain new knowledge" },
    { word: "BOOKS", category: "Items", hint: "Pages with stories" },
    { word: "WRITE", category: "Action", hint: "Use a pen to make words" },
    { word: "STUDY", category: "Action", hint: "Spend time to understand" },
    { word: "PAPER", category: "Items", hint: "Material for writing" },
    { word: "FRIEND", category: "People", hint: "Someone you enjoy with" },
    {
      word: "VILLAGE",
      category: "Place",
      hint: "Small settlement in the country",
    },
    { word: "LISTEN", category: "Action", hint: "Pay attention to sounds" },
    { word: "STORY", category: "Knowledge", hint: "A tale of events" },
    { word: "TRUTH", category: "Concept", hint: "That which is correct" },
    { word: "MASTER", category: "People", hint: "One with great skill" },
    { word: "DHARMA", category: "Sacred", hint: "Duty or cosmic order" },
    { word: "LESSON", category: "Knowledge", hint: "A period of learning" },
    { word: "SIMPLE", category: "Adj", hint: "Easy to understand" },
    { word: "TEACHER", category: "People", hint: "One who lights the mind" },
    { word: "CLASS", category: "Place", hint: "Where lessons gather" },
    {
      word: "BLACKBOARD",
      category: "Item",
      hint: "Dark wall where chalk speaks",
    },
    { word: "PEN", category: "Item", hint: "Tool that bleeds ink" },
    { word: "NOTE", category: "Item", hint: "Small memory on paper" },
    { word: "EXAM", category: "Event", hint: "A test of knowledge" },
    { word: "MARKS", category: "Concept", hint: "Numbers that measure effort" },
    {
      word: "KNOWLEDGE",
      category: "Concept",
      hint: "Treasure that grows when shared",
    },
    { word: "PENCIL", category: "Item", hint: "Writes but can be erased" },
    { word: "ERASER", category: "Item", hint: "Makes mistakes vanish" },
    { word: "BOARD", category: "Item", hint: "Surface for writing lessons" },
    { word: "UNIFORM", category: "Item", hint: "Clothes that make all equal" },
    { word: "BELL", category: "Item", hint: "Sound that begins or ends" },
    {
      word: "QUIZ",
      category: "Event",
      hint: "Questions that test quick minds",
    },
    { word: "ANSWER", category: "Concept", hint: "The key to a question" },
    { word: "PUPIL", category: "People", hint: "Learner under guidance" },
    { word: "BOARDING", category: "Place", hint: "School where you also live" },
    {
      word: "EXERCISE",
      category: "Action",
      hint: "Practice that sharpens skill",
    },
    { word: "HISTORY", category: "Knowledge", hint: "Stories of the past" },
    {
      word: "GEOGRAPHY",
      category: "Knowledge",
      hint: "Maps and lands explained",
    },
    {
      word: "SCIENCE",
      category: "Knowledge",
      hint: "Truths of nature revealed",
    },
    { word: "MATH", category: "Knowledge", hint: "Numbers that never lie" },
    { word: "ART", category: "Knowledge", hint: "Colors that speak silently" },
    {
      word: "MUSIC",
      category: "Knowledge",
      hint: "Sounds that soothe the soul",
    },
    { word: "SPORT", category: "Action", hint: "Games that test strength" },
    { word: "PLAYGROUND", category: "Place", hint: "Where laughter runs free" },
    { word: "LIBRARY", category: "Place", hint: "Silent hall of wisdom" },
    { word: "PRINCIPAL", category: "People", hint: "Head of the school" },
    { word: "PROJECT", category: "Action", hint: "Work done to show learning" },
    { word: "RESEARCH", category: "Action", hint: "Seek facts and evidence" },
    { word: "DEBATE", category: "Action", hint: "Argue ideas with reason" },
  ],
  5: [
    { word: "TEMPLE", category: "Place", hint: "Walls whisper to heaven" },
    { word: "MARKET", category: "Place", hint: "Coins sing, voices clash" },
    { word: "PRAYER", category: "Action", hint: "Silent words reach sky" },
    { word: "MORNING", category: "Time", hint: "Light breaks the dark" },
    { word: "BELIEF", category: "Concept", hint: "Invisible anchor of mind" },
    { word: "PEOPLE", category: "Society", hint: "Many hearts, one crowd" },
    { word: "GATHER", category: "Action", hint: "Hands meet, voices join" },
    { word: "SACRED", category: "Adj", hint: "Untouchable, yet revered" },
    { word: "STREET", category: "Place", hint: "Stone veins of the city" },
    { word: "BRIGHT", category: "Adj", hint: "Eyes squint at its touch" },
    { word: "FAMILY", category: "Society", hint: "Roots bound by blood" },
    { word: "FAITH", category: "Emotion", hint: "Bridge built without sight" },
    { word: "SILVER", category: "Items", hint: "Moon’s metal, cold shine" },
    {
      word: "INCENSE",
      category: "Items",
      hint: "Smoke carries devotion upward",
    },
    { word: "CHURCH", category: "Place", hint: "Echoes of hymns linger" },
    { word: "ALTAR", category: "Place", hint: "Stone table for gods" },
    { word: "CANDLE", category: "Item", hint: "Wax spine holds fire" },
    { word: "CHANT", category: "Action", hint: "Echo repeated until truth" },
    { word: "OATH", category: "Concept", hint: "Words chained to honor" },
    { word: "RING", category: "Item", hint: "Circle that binds forever" },
    { word: "DRUM", category: "Item", hint: "Heartbeat carved in wood" },
    { word: "SONG", category: "Action", hint: "Air dressed in melody" },
    { word: "FESTIVAL", category: "Event", hint: "Days when colors dance" },
    { word: "LAMP", category: "Item", hint: "Glass cage for flame" },
    { word: "TOWER", category: "Place", hint: "Stone finger points skyward" },
    { word: "BELL", category: "Item", hint: "Metal tongue calls time" },
    { word: "FEAST", category: "Event", hint: "Tables heavy with joy" },
    { word: "CROWN", category: "Item", hint: "Circle of power worn" },
    { word: "KING", category: "People", hint: "Voice rules, crown shines" },
    { word: "QUEEN", category: "People", hint: "Grace beside the throne" },
    {
      word: "PRIEST",
      category: "People",
      hint: "Messenger between earth and sky",
    },
    { word: "MONK", category: "People", hint: "Silence becomes his speech" },
    { word: "PILGRIM", category: "People", hint: "Traveler with sacred steps" },
    { word: "FIRE", category: "Nature", hint: "Devourer that warms too" },
    { word: "ASH", category: "Nature", hint: "What flame leaves behind" },
    { word: "SPIRIT", category: "Concept", hint: "Breath unseen, eternal" },
    { word: "SOUL", category: "Concept", hint: "Traveler within the body" },
    { word: "RITUAL", category: "Action", hint: "Steps repeated for unseen" },
    { word: "OFFERING", category: "Action", hint: "Gift laid before silence" },
    { word: "MASK", category: "Item", hint: "Face that hides truth" },
    { word: "DOOR", category: "Item", hint: "Wood that opens worlds" },
    { word: "WINDOW", category: "Item", hint: "House’s eye to sky" },
    { word: "BRIDGE", category: "Place", hint: "Stone spine across water" },
    { word: "WELL", category: "Place", hint: "Depth that holds thirst" },
    { word: "CLOCK", category: "Item", hint: "Circle that eats hours" },
    { word: "DESTINY", category: "Concept", hint: "Path written before steps" },
    { word: "HOPE", category: "Emotion", hint: "Light carried in dark" },
    { word: "LOVE", category: "Emotion", hint: "Bond unseen yet unbroken" },
    { word: "CAVE", category: "Place", hint: "Earth’s mouth of shadow" },
    { word: "CITY", category: "Place", hint: "Crowds, towers, endless hum" },
  ],
  6: [
    {
      word: "SILENCE",
      category: "State",
      hint: "The complete absence of sound",
    },
    {
      word: "ANCIENT",
      category: "Time",
      hint: "Belonging to the very distant past",
    },
    { word: "STREAM", category: "Nature", hint: "A small, narrow river" },
    {
      word: "FOREST",
      category: "Place",
      hint: "A large area covered chiefly with trees",
    },
    {
      word: "JOURNEY",
      category: "Action",
      hint: "The act of traveling from one place to another",
    },
    {
      word: "WILDERNESS",
      category: "Nature",
      hint: "An uncultivated and uninhabited region",
    },
    {
      word: "VALLEY",
      category: "Nature",
      hint: "Low area between hills or mountains",
    },
    {
      word: "MYSTERY",
      category: "Concept",
      hint: "Something that is difficult to explain",
    },
    {
      word: "WALKING",
      category: "Action",
      hint: "Moving at a regular pace by foot",
    },
    {
      word: "NATURAL",
      category: "Adj",
      hint: "Existing in or derived from nature",
    },
    {
      word: "HARMONY",
      category: "Concept",
      hint: "The quality of forming a pleasing whole",
    },
    {
      word: "WONDER",
      category: "Emotion",
      hint: "A feeling of surprise and admiration",
    },
    {
      word: "SHADOW",
      category: "Nature",
      hint: "A dark area produced by an object blocking light",
    },
    {
      word: "SPIRIT",
      category: "Concept",
      hint: "The non-physical part of a person",
    },
    {
      word: "HUNTER",
      category: "People",
      hint: "A person or animal that hunts for food",
    },
  ],
  7: [
    {
      word: "KINGDOM",
      category: "Society",
      hint: "A country or state ruled by a monarch",
    },
    {
      word: "JUSTICE",
      category: "Concept",
      hint: "Fairness in the way people are treated",
    },
    {
      word: "PALACE",
      category: "Place",
      hint: "The official residence of a sovereign",
    },
    {
      word: "ADVISOR",
      category: "People",
      hint: "A person who gives suggestions or guidance",
    },
    {
      word: "HISTORY",
      category: "Knowledge",
      hint: "The study of past events",
    },
    {
      word: "CROWNED",
      category: "Adj",
      hint: "Bearing a symbol of royal power on the head",
    },
    {
      word: "SOLDIER",
      category: "People",
      hint: "A person who serves in an army",
    },
    {
      word: "FREEDOM",
      category: "Concept",
      hint: "The power or right to act as one wants",
    },
    {
      word: "COURAGE",
      category: "Emotion",
      hint: "Strength in the face of pain or grief",
    },
    {
      word: "NOBLEMAN",
      category: "People",
      hint: "A man who belongs to the highest social class",
    },
    {
      word: "COMMAND",
      category: "Action",
      hint: "To give an authoritative order",
    },
    {
      word: "DEFEND",
      category: "Action",
      hint: "To protect from harm or danger",
    },
    {
      word: "HONOR",
      category: "Concept",
      hint: "High respect or great esteem",
    },
    {
      word: "SUCCESS",
      category: "Concept",
      hint: "The accomplishment of an aim or purpose",
    },
    {
      word: "ORATOR",
      category: "People",
      hint: "A public speaker of great eloquence",
    },
  ],
  8: [
    {
      word: "CURRENT",
      category: "Nature",
      hint: "The flow of water or electricity",
    },
    {
      word: "OCEANS",
      category: "Nature",
      hint: "The vast bodies of salt water covering Earth",
    },
    {
      word: "ETERNAL",
      category: "Concept",
      hint: "Lasting or existing forever",
    },
    {
      word: "POWERFUL",
      category: "Adj",
      hint: "Having great strength or influence",
    },
    {
      word: "GUIDANCE",
      category: "Concept",
      hint: "Direction or advice provided for a path",
    },
    {
      word: "FLOWING",
      category: "Action",
      hint: "Moving steadily and continuously in a stream",
    },
    {
      word: "RIPPLES",
      category: "Nature",
      hint: "Small waves on the surface of water",
    },
    {
      word: "UNBROKEN",
      category: "Adj",
      hint: "Continuous and not interrupted",
    },
    {
      word: "DEEPNESS",
      category: "Adj",
      hint: "The quality of extending far down from the surface",
    },
    {
      word: "SURRENDER",
      category: "Action",
      hint: "To cease resistance and submit",
    },
    {
      word: "CROSSING",
      category: "Action",
      hint: "The act of going from one side to the other",
    },
    {
      word: "ENDLESS",
      category: "Adj",
      hint: "Having or seeming to have no limit",
    },
    {
      word: "WISDOM",
      category: "Knowledge",
      hint: "The quality of having experience and good judgment",
    },
    {
      word: "BRIDGES",
      category: "Place",
      hint: "Structures carrying paths over obstacles",
    },
    {
      word: "SAILING",
      category: "Action",
      hint: "The action of traveling in a ship with sails",
    },
  ],
  9: [
    {
      word: "RADIANCE",
      category: "State",
      hint: "Light or heat as emitted by something",
    },
    {
      word: "CELESTIAL",
      category: "Cosmic",
      hint: "Belonging or relating to the heavens",
    },
    {
      word: "CHARIOT",
      category: "Vehicle",
      hint: "A two-wheeled horse-drawn vehicle of antiquity",
    },
    {
      word: "INFINITE",
      category: "Concept",
      hint: "Limitless or endless in space or size",
    },
    { word: "ETERNITY", category: "Time", hint: "Infinite or unending time" },
    {
      word: "GLORIOUS",
      category: "Adj",
      hint: "Having or deserving fame and admiration",
    },
    {
      word: "HEAVENS",
      category: "Cosmic",
      hint: "The region surrounding the earth in outer space",
    },
    {
      word: "LIGHTNING",
      category: "Nature",
      hint: "A sudden spark of electricity in the sky",
    },
    {
      word: "UNIVERSE",
      category: "Cosmic",
      hint: "All existing matter and space as a whole",
    },
    {
      word: "DEVOTION",
      category: "Emotion",
      hint: "Love, loyalty, or enthusiasm for a cause",
    },
    {
      word: "KNOWLEDGE",
      category: "Concept",
      hint: "Facts, information, and skills acquired",
    },
    {
      word: "BRILLIANT",
      category: "Adj",
      hint: "Exceptionally clever or talented; or very bright",
    },
    {
      word: "ABSOLUTE",
      category: "Adj",
      hint: "Not qualified or diminished in any way; total",
    },
    {
      word: "CREATOR",
      category: "People",
      hint: "A person or thing that brings something into existence",
    },
    {
      word: "PROPHECY",
      category: "Sacred",
      hint: "A prediction of what will happen in the future",
    },
  ],
  10: [
    {
      word: "CONSCIOUS",
      category: "Philosophy",
      hint: "Aware of and responding to one's surroundings",
    },
    {
      word: "MANDALA",
      category: "Sacred",
      hint: "A geometric figure representing the universe",
    },
    {
      word: "ENLIGHTEN",
      category: "Action",
      hint: "To give someone greater knowledge and understanding",
    },
    {
      word: "EXISTENCE",
      category: "Concept",
      hint: "The fact or state of living or having objective reality",
    },
    {
      word: "LIBERATION",
      category: "Concept",
      hint: "The act of setting someone free from imprisonment",
    },
    {
      word: "MEDITATION",
      category: "Action",
      hint: "A practice of focus to achieve mental clarity",
    },
    {
      word: "DIMENSION",
      category: "Cosmic",
      hint: "A measurable extent of some kind, like length",
    },
    {
      word: "AWAKENING",
      category: "State",
      hint: "An act of waking from sleep or coming to realize",
    },
    {
      word: "BOUNDLESS",
      category: "Adj",
      hint: "Immense in scope; having no boundaries",
    },
    {
      word: "COSMOLOGY",
      category: "Science",
      hint: "The science of the origin and development of the universe",
    },
    {
      word: "TRANSCEND",
      category: "Action",
      hint: "To rise above or go beyond the limits of",
    },
    {
      word: "VIBRATION",
      category: "Science",
      hint: "An oscillation of the parts of a fluid or elastic solid",
    },
    {
      word: "ULTIMATE",
      category: "Adj",
      hint: "Being or happening at the end of a process",
    },
    {
      word: "DUALITY",
      category: "Philosophy",
      hint: "The quality of being comprised of two parts",
    },
    {
      word: "OMNIPRESENT",
      category: "Adj",
      hint: "Widely or constantly encountered; widespread",
    },
  ],
};

// 4. ECONOMY & REWARDS
export const GAME_STAKES = {
  ONLINE_1V1: {
    ENTRY_FEE: 10,
    BASE_WIN_PRIZE: 20,
    BASE_XP_WIN: 25,
    XP_LOSS: 5,
    STREAK_XP_BONUS: 15,
  },
  CLASSIC: {
    BASE_XP: 15,
    BASE_COINS: 5,
    XP_LOSS_PER_LIFE: 2,
    STREAK_BONUS_MULTIPLIER: 1.5,
  },
  ENDLESS: {
    HEALTH_BONUS_XP: 10, // XP per remaining life at the end of a word
    HEALTH_BONUS_COINS: 2, // Coins per remaining life
  },
  ENERGY: { MAX_LIVES: 10, RECOVERY_MINUTES: 180 },

  // Logic: Bonus = 100 * Level (Triggered when level changes)
  getArenaUnlockBonus: (level) => 100 * level,
};

// constants.js

export const GAME_CONFIG = {
  MAX_WRONG_GUESSES: 6,
  DAILY_XP_REWARD: 50,
  DAILY_COIN_REWARD: 20,
  DAILY_PERFECT_BONUS: 20,
};
