// constants.js
// 1. ARENA CONFIGURATION
// We use "Atmospheric" backgrounds (Zinc/Slate) so the Rank colors pop.
export const ARENAS = {
  1: {
    id: 1,
    name: "The Inner Seed",
    arenaBg: "bg-zinc-50 dark:bg-zinc-900",
    description: "The beginning of sound.",
  },
  2: {
    id: 2,
    name: "The Mother's Lap",
    arenaBg: "bg-stone-50 dark:bg-stone-900",
    description: "Domestic comfort and warmth.",
  },
  3: {
    id: 3,
    name: "The Tulsi Courtyard",
    arenaBg: "bg-slate-50 dark:bg-slate-900",
    description: "Nature within the household.",
  },
  4: {
    id: 4,
    name: "The Village Gurukul",
    arenaBg: "bg-zinc-100 dark:bg-zinc-900",
    description: "Learning in the community.",
  },
  5: {
    id: 5,
    name: "The Temple Square",
    arenaBg: "bg-stone-100 dark:bg-stone-900",
    description: "Social and spiritual connection.",
  },
  6: {
    id: 6,
    name: "The Forest Path",
    arenaBg: "bg-zinc-50 dark:bg-zinc-950",
    description: "Venturing into the wild unknown.",
  },
  7: {
    id: 7,
    name: "The Royal Court",
    arenaBg: "bg-slate-100 dark:bg-zinc-950",
    description: "Governance and honor.",
  },
  8: {
    id: 8,
    name: "The Great River",
    arenaBg: "bg-blue-50/30 dark:bg-zinc-950",
    description: "World's wisdom.",
  },
  9: {
    id: 9,
    name: "The Solar Chariot",
    arenaBg: "bg-orange-50/20 dark:bg-zinc-950",
    description: "Cosmic light.",
  },
  10: {
    id: 10,
    name: "The Cosmic Dance",
    arenaBg: "bg-zinc-950",
    description: "Unity with the infinite.",
  },
};

// 2. RANK CONFIGURATION
// These colors now drive EVERY accent in the game (Balloons, Buttons, Overlays)
export const RANKS = [
  {
    level: 1,
    name: "Infant",
    arenaId: 1,
    minXP: 0,
    maxTries: 10,
    color: "#75c32c",
    stageName: ARENAS[1].name,
  },
  {
    level: 2,
    name: "Toddler",
    arenaId: 2,
    minXP: 200,
    maxTries: 10,
    color: "#a2d149",
    stageName: ARENAS[2].name,
  },
  {
    level: 3,
    name: "Student",
    arenaId: 3,
    minXP: 400,
    maxTries: 9,
    color: "#d4e157",
    stageName: ARENAS[3].name,
  },
  {
    level: 4,
    name: "Scholar",
    arenaId: 4,
    minXP: 600,
    maxTries: 8,
    color: "#ffee58",
    stageName: ARENAS[4].name,
  },
  {
    level: 5,
    name: "Sage",
    arenaId: 5,
    minXP: 800,
    maxTries: 8,
    color: "#ffca28",
    stageName: ARENAS[5].name,
  },
  {
    level: 6,
    name: "Yogi",
    arenaId: 6,
    minXP: 1000,
    maxTries: 7,
    color: "#ff8f00",
    stageName: ARENAS[6].name,
  },
  {
    level: 7,
    name: "Guru",
    arenaId: 7,
    minXP: 1200,
    maxTries: 7,
    color: "#f4511e",
    stageName: ARENAS[7].name,
  },
  {
    level: 8,
    name: "Master",
    arenaId: 8,
    minXP: 1400,
    maxTries: 6,
    color: "#d84315",
    stageName: ARENAS[8].name,
  },
  {
    level: 9,
    name: "Legend",
    arenaId: 9,
    minXP: 1600,
    maxTries: 6,
    color: "#b71c1c",
    stageName: ARENAS[9].name,
  },
  {
    level: 10,
    name: "Word Papa",
    arenaId: 10,
    minXP: 1800,
    maxTries: 5,
    color: "#4a148c",
    stageName: ARENAS[10].name,
  },
];

// 3. WORDS POOL (15 words per stage)
export const WORDS_POOL = {
  1: [
    { word: "SUN", category: "Nature", hint: "The big yellow ball in the sky" },
    { word: "SKY", category: "Nature", hint: "It is blue and has clouds" },
    { word: "MUD", category: "Nature", hint: "Wet dirt you find after rain" },
    { word: "ONE", category: "Number", hint: "The number after zero" },
    { word: "AIR", category: "Nature", hint: "You breathe this in" },
    { word: "DAY", category: "Time", hint: "When it is light outside" },
    { word: "CAT", category: "Animal", hint: "A pet that says meow" },
    { word: "SON", category: "Family", hint: "A male child" },
    { word: "EAR", category: "Body", hint: "You use this to hear sounds" },
    { word: "EAT", category: "Action", hint: "To put food in your mouth" },
    { word: "RUN", category: "Action", hint: "To move very fast on your feet" },
    { word: "SIT", category: "Action", hint: "To rest on a chair" },
    { word: "BIG", category: "Adjective", hint: "The opposite of small" },
    { word: "RED", category: "Color", hint: "The color of an apple" },
    { word: "DOG", category: "Animal", hint: "A pet that barks" },
    { word: "TWO", category: "Number", hint: "Comes after one" },
    { word: "MOON", category: "Nature", hint: "Shines at night in the sky" },
    { word: "SEA", category: "Nature", hint: "Large body of salt water" },
    { word: "MAN", category: "Family", hint: "An adult male" },
    { word: "MOM", category: "Family", hint: "Another word for mother" },
    { word: "LEG", category: "Body", hint: "You use this to walk" },
    { word: "EYE", category: "Body", hint: "You use this to see" },
    { word: "HAT", category: "Object", hint: "You wear this on your head" },
    { word: "CAR", category: "Object", hint: "A vehicle with four wheels" },
    { word: "BED", category: "Object", hint: "You sleep on this" },
    { word: "TOY", category: "Object", hint: "Children play with this" },
    { word: "FAN", category: "Object", hint: "It blows air to cool you" },
    { word: "ICE", category: "Nature", hint: "Frozen water" },
    { word: "COW", category: "Animal", hint: "Gives milk" },
    { word: "PIG", category: "Animal", hint: "Lives on a farm and oinks" },
    { word: "BAT", category: "Animal", hint: "A flying mammal at night" },
    { word: "ANT", category: "Animal", hint: "A tiny insect that crawls" },
    { word: "TEN", category: "Number", hint: "Comes after nine" },
    { word: "HOT", category: "Adjective", hint: "The opposite of cold" },
    { word: "WET", category: "Adjective", hint: "The opposite of dry" },
    { word: "BOX", category: "Object", hint: "You can put things inside" },
    { word: "PAN", category: "Object", hint: "Used for cooking food" },
    { word: "PEN", category: "Object", hint: "You write with this" },
    { word: "MAP", category: "Object", hint: "Shows places and roads" },
    { word: "BEE", category: "Animal", hint: "Makes honey" },
    { word: "HEN", category: "Animal", hint: "A bird that lays eggs" },
    { word: "RAT", category: "Animal", hint: "Looks like a big mouse" },
    { word: "SUN", category: "Nature", hint: "The star that gives us light" },
    { word: "ZIP", category: "Object", hint: "Used to close clothes or bags" },
    { word: "TOP", category: "Object", hint: "The highest part of something" },
    { word: "CUP", category: "Object", hint: "You drink from this" },
    { word: "HOP", category: "Action", hint: "To jump on one foot" },
    { word: "WIN", category: "Action", hint: "The opposite of lose" },
    {
      word: "FUN",
      category: "Adjective",
      hint: "Something that makes you happy",
    },
    { word: "NEW", category: "Adjective", hint: "The opposite of old" },
  ],
  2: [
    { word: "MILK", category: "Food", hint: "Often poured on cereal" },
    {
      word: "BOWL",
      category: "Home",
      hint: "Round container for holding things",
    },
    {
      word: "LOVE",
      category: "Emotion",
      hint: "What hearts usually stand for",
    },
    {
      word: "HOME",
      category: "Place",
      hint: "Where you return after being away",
    },
    { word: "PRAY", category: "Action", hint: "Done quietly with closed eyes" },
    { word: "KIND", category: "Adj", hint: "The opposite of mean" },
    { word: "BABY", category: "Family", hint: "Sleeps a lot and cries often" },
    { word: "HAND", category: "Body", hint: "Used to wave or hold things" },
    { word: "FOOD", category: "Home", hint: "Needed for energy each day" },
    {
      word: "MOON",
      category: "Nature",
      hint: "Changes shape across the month",
    },
    {
      word: "STAR",
      category: "Nature",
      hint: "Seen shining far away at night",
    },
    { word: "SOFT", category: "Adj", hint: "Not hard when you touch it" },
    {
      word: "PLAY",
      category: "Action",
      hint: "Children spend time doing this",
    },
    { word: "SING", category: "Action", hint: "Done with rhythm and melody" },
    { word: "GIVE", category: "Action", hint: "The opposite of keep" },
    { word: "BOOK", category: "Object", hint: "Has pages you can turn" },
    { word: "CHAIR", category: "Home", hint: "Something you sit on" },
    { word: "WALL", category: "Home", hint: "Keeps rooms apart" },
    { word: "RICE", category: "Food", hint: "Tiny grains cooked for meals" },
    { word: "CAKE", category: "Food", hint: "Often eaten at birthdays" },
    { word: "TEA", category: "Food", hint: "A hot drink made with leaves" },
    { word: "FISH", category: "Animal", hint: "Lives in water and swims" },
    { word: "BIRD", category: "Animal", hint: "Has wings and can fly" },
    { word: "TREE", category: "Nature", hint: "Has roots, trunk, and leaves" },
    { word: "RAIN", category: "Nature", hint: "Falls from clouds" },
    { word: "SNOW", category: "Nature", hint: "Cold flakes from the sky" },
    { word: "WIND", category: "Nature", hint: "Moves leaves and kites" },
    { word: "FIRE", category: "Nature", hint: "Gives heat and light" },
    { word: "CUP", category: "Home", hint: "Used for drinking" },
    { word: "DOOR", category: "Home", hint: "You open it to enter" },
    { word: "KEY", category: "Object", hint: "Used to unlock things" },
    { word: "BAG", category: "Object", hint: "Carries your belongings" },
    { word: "BOX", category: "Object", hint: "Keeps things inside" },
    { word: "TOY", category: "Object", hint: "Children enjoy playing with it" },
    { word: "DOLL", category: "Object", hint: "Looks like a small person" },
    { word: "BALL", category: "Object", hint: "Round and used in games" },
    { word: "HAT", category: "Object", hint: "Worn on the head" },
    { word: "SHOE", category: "Object", hint: "Covers your foot" },
    { word: "SOAP", category: "Home", hint: "Used with water to clean" },
    { word: "CLOCK", category: "Home", hint: "Tells the time" },
    { word: "ROAD", category: "Place", hint: "Cars move along it" },
    { word: "CITY", category: "Place", hint: "Has many buildings and people" },
    { word: "PARK", category: "Place", hint: "Open area with grass and trees" },
    { word: "SHOP", category: "Place", hint: "Where you buy things" },
    { word: "SCHOOL", category: "Place", hint: "Children go here to learn" },
    { word: "WORK", category: "Action", hint: "Adults spend time doing this" },
    { word: "READ", category: "Action", hint: "Done with books or papers" },
    { word: "WRITE", category: "Action", hint: "Done with a pen or pencil" },
    { word: "DRAW", category: "Action", hint: "Making pictures on paper" },
    { word: "JUMP", category: "Action", hint: "Both feet leave the ground" },
  ],

  3: [
    { word: "GARDEN", category: "Place", hint: "A place where flowers grow" },
    { word: "FLOWER", category: "Nature", hint: "Colorful part of a plant" },
    { word: "FRUIT", category: "Food", hint: "Sweet food like mango or apple" },
    { word: "PLANT", category: "Nature", hint: "It grows from a seed in soil" },
    { word: "WATER", category: "Nature", hint: "You drink it when thirsty" },
    { word: "GREEN", category: "Color", hint: "The color of most leaves" },
    { word: "SMALL", category: "Adj", hint: "Not taking up much space" },
    { word: "BIRD", category: "Animal", hint: "It has wings and can fly" },
    { word: "SWEET", category: "Food", hint: "Tastes like sugar or honey" },
    { word: "SHADE", category: "Nature", hint: "Cool area away from the sun" },
    { word: "TULSI", category: "Sacred", hint: "A holy basil plant" },
    { word: "LEAF", category: "Nature", hint: "A green part of a tree branch" },
    { word: "SMILE", category: "Emotion", hint: "A happy look on your face" },
    {
      word: "ROOTS",
      category: "Nature",
      hint: "The part of a plant under the ground",
    },
    { word: "CLEAN", category: "Adj", hint: "Free from dirt or marks" },
  ],
  4: [
    { word: "SCHOOL", category: "Place", hint: "A building for education" },
    { word: "LEARN", category: "Action", hint: "To gain new knowledge" },
    { word: "BOOKS", category: "Items", hint: "Pages of paper with stories" },
    { word: "WRITE", category: "Action", hint: "Using a pen to make words" },
    {
      word: "STUDY",
      category: "Action",
      hint: "Spending time to understand a topic",
    },
    {
      word: "PAPER",
      category: "Items",
      hint: "Material made from trees for writing",
    },
    {
      word: "FRIEND",
      category: "People",
      hint: "Someone you enjoy spending time with",
    },
    {
      word: "VILLAGE",
      category: "Place",
      hint: "A small settlement in the country",
    },
    { word: "LISTEN", category: "Action", hint: "Paying attention to sounds" },
    {
      word: "STORY",
      category: "Knowledge",
      hint: "A tale of events, real or imaginary",
    },
    {
      word: "TRUTH",
      category: "Concept",
      hint: "That which is factually correct",
    },
    {
      word: "MASTER",
      category: "People",
      hint: "One who has great skill or authority",
    },
    {
      word: "DHARMA",
      category: "Sacred",
      hint: "The eternal and inherent nature of reality",
    },
    {
      word: "LESSON",
      category: "Knowledge",
      hint: "A period of learning or a moral",
    },
    { word: "SIMPLE", category: "Adj", hint: "Easy to understand or do" },
  ],
  5: [
    {
      word: "TEMPLE",
      category: "Place",
      hint: "A house of worship and prayer",
    },
    {
      word: "MARKET",
      category: "Place",
      hint: "Where people buy and sell goods",
    },
    {
      word: "PRAYER",
      category: "Action",
      hint: "An earnest hope or spiritual address",
    },
    {
      word: "MORNING",
      category: "Time",
      hint: "The period from sunrise to noon",
    },
    {
      word: "BELIEF",
      category: "Concept",
      hint: "Acceptance that something is true",
    },
    { word: "PEOPLE", category: "Society", hint: "Human beings in general" },
    {
      word: "GATHER",
      category: "Action",
      hint: "To bring together in one group",
    },
    {
      word: "SACRED",
      category: "Adj",
      hint: "Connected with God or dedicated to a religious purpose",
    },
    {
      word: "STREET",
      category: "Place",
      hint: "A public road in a city or town",
    },
    {
      word: "BRIGHT",
      category: "Adj",
      hint: "Giving out or reflecting a lot of light",
    },
    {
      word: "FAMILY",
      category: "Society",
      hint: "A group of one or more parents and children",
    },
    {
      word: "FAITH",
      category: "Emotion",
      hint: "Complete trust or confidence in someone",
    },
    { word: "SILVER", category: "Items", hint: "A shiny grey precious metal" },
    {
      word: "INCENSE",
      category: "Items",
      hint: "A substance burned for its sweet smell",
    },
    {
      word: "CHURCH",
      category: "Place",
      hint: "A place for public Christian worship",
    },
  ],
  6: [
    {
      word: "SILENCE",
      category: "State",
      hint: "The complete absence of sound",
    },
    {
      word: "ANCIENT",
      category: "Time",
      hint: "Belonging to the very distant past",
    },
    { word: "STREAM", category: "Nature", hint: "A small, narrow river" },
    {
      word: "FOREST",
      category: "Place",
      hint: "A large area covered chiefly with trees",
    },
    {
      word: "JOURNEY",
      category: "Action",
      hint: "The act of traveling from one place to another",
    },
    {
      word: "WILDERNESS",
      category: "Nature",
      hint: "An uncultivated and uninhabited region",
    },
    {
      word: "VALLEY",
      category: "Nature",
      hint: "Low area between hills or mountains",
    },
    {
      word: "MYSTERY",
      category: "Concept",
      hint: "Something that is difficult to explain",
    },
    {
      word: "WALKING",
      category: "Action",
      hint: "Moving at a regular pace by foot",
    },
    {
      word: "NATURAL",
      category: "Adj",
      hint: "Existing in or derived from nature",
    },
    {
      word: "HARMONY",
      category: "Concept",
      hint: "The quality of forming a pleasing whole",
    },
    {
      word: "WONDER",
      category: "Emotion",
      hint: "A feeling of surprise and admiration",
    },
    {
      word: "SHADOW",
      category: "Nature",
      hint: "A dark area produced by an object blocking light",
    },
    {
      word: "SPIRIT",
      category: "Concept",
      hint: "The non-physical part of a person",
    },
    {
      word: "HUNTER",
      category: "People",
      hint: "A person or animal that hunts for food",
    },
  ],
  7: [
    {
      word: "KINGDOM",
      category: "Society",
      hint: "A country or state ruled by a monarch",
    },
    {
      word: "JUSTICE",
      category: "Concept",
      hint: "Fairness in the way people are treated",
    },
    {
      word: "PALACE",
      category: "Place",
      hint: "The official residence of a sovereign",
    },
    {
      word: "ADVISOR",
      category: "People",
      hint: "A person who gives suggestions or guidance",
    },
    {
      word: "HISTORY",
      category: "Knowledge",
      hint: "The study of past events",
    },
    {
      word: "CROWNED",
      category: "Adj",
      hint: "Bearing a symbol of royal power on the head",
    },
    {
      word: "SOLDIER",
      category: "People",
      hint: "A person who serves in an army",
    },
    {
      word: "FREEDOM",
      category: "Concept",
      hint: "The power or right to act as one wants",
    },
    {
      word: "COURAGE",
      category: "Emotion",
      hint: "Strength in the face of pain or grief",
    },
    {
      word: "NOBLEMAN",
      category: "People",
      hint: "A man who belongs to the highest social class",
    },
    {
      word: "COMMAND",
      category: "Action",
      hint: "To give an authoritative order",
    },
    {
      word: "DEFEND",
      category: "Action",
      hint: "To protect from harm or danger",
    },
    {
      word: "HONOR",
      category: "Concept",
      hint: "High respect or great esteem",
    },
    {
      word: "SUCCESS",
      category: "Concept",
      hint: "The accomplishment of an aim or purpose",
    },
    {
      word: "ORATOR",
      category: "People",
      hint: "A public speaker of great eloquence",
    },
  ],
  8: [
    {
      word: "CURRENT",
      category: "Nature",
      hint: "The flow of water or electricity",
    },
    {
      word: "OCEANS",
      category: "Nature",
      hint: "The vast bodies of salt water covering Earth",
    },
    {
      word: "ETERNAL",
      category: "Concept",
      hint: "Lasting or existing forever",
    },
    {
      word: "POWERFUL",
      category: "Adj",
      hint: "Having great strength or influence",
    },
    {
      word: "GUIDANCE",
      category: "Concept",
      hint: "Direction or advice provided for a path",
    },
    {
      word: "FLOWING",
      category: "Action",
      hint: "Moving steadily and continuously in a stream",
    },
    {
      word: "RIPPLES",
      category: "Nature",
      hint: "Small waves on the surface of water",
    },
    {
      word: "UNBROKEN",
      category: "Adj",
      hint: "Continuous and not interrupted",
    },
    {
      word: "DEEPNESS",
      category: "Adj",
      hint: "The quality of extending far down from the surface",
    },
    {
      word: "SURRENDER",
      category: "Action",
      hint: "To cease resistance and submit",
    },
    {
      word: "CROSSING",
      category: "Action",
      hint: "The act of going from one side to the other",
    },
    {
      word: "ENDLESS",
      category: "Adj",
      hint: "Having or seeming to have no limit",
    },
    {
      word: "WISDOM",
      category: "Knowledge",
      hint: "The quality of having experience and good judgment",
    },
    {
      word: "BRIDGES",
      category: "Place",
      hint: "Structures carrying paths over obstacles",
    },
    {
      word: "SAILING",
      category: "Action",
      hint: "The action of traveling in a ship with sails",
    },
  ],
  9: [
    {
      word: "RADIANCE",
      category: "State",
      hint: "Light or heat as emitted by something",
    },
    {
      word: "CELESTIAL",
      category: "Cosmic",
      hint: "Belonging or relating to the heavens",
    },
    {
      word: "CHARIOT",
      category: "Vehicle",
      hint: "A two-wheeled horse-drawn vehicle of antiquity",
    },
    {
      word: "INFINITE",
      category: "Concept",
      hint: "Limitless or endless in space or size",
    },
    { word: "ETERNITY", category: "Time", hint: "Infinite or unending time" },
    {
      word: "GLORIOUS",
      category: "Adj",
      hint: "Having or deserving fame and admiration",
    },
    {
      word: "HEAVENS",
      category: "Cosmic",
      hint: "The region surrounding the earth in outer space",
    },
    {
      word: "LIGHTNING",
      category: "Nature",
      hint: "A sudden spark of electricity in the sky",
    },
    {
      word: "UNIVERSE",
      category: "Cosmic",
      hint: "All existing matter and space as a whole",
    },
    {
      word: "DEVOTION",
      category: "Emotion",
      hint: "Love, loyalty, or enthusiasm for a cause",
    },
    {
      word: "KNOWLEDGE",
      category: "Concept",
      hint: "Facts, information, and skills acquired",
    },
    {
      word: "BRILLIANT",
      category: "Adj",
      hint: "Exceptionally clever or talented; or very bright",
    },
    {
      word: "ABSOLUTE",
      category: "Adj",
      hint: "Not qualified or diminished in any way; total",
    },
    {
      word: "CREATOR",
      category: "People",
      hint: "A person or thing that brings something into existence",
    },
    {
      word: "PROPHECY",
      category: "Sacred",
      hint: "A prediction of what will happen in the future",
    },
  ],
  10: [
    {
      word: "CONSCIOUS",
      category: "Philosophy",
      hint: "Aware of and responding to one's surroundings",
    },
    {
      word: "MANDALA",
      category: "Sacred",
      hint: "A geometric figure representing the universe",
    },
    {
      word: "ENLIGHTEN",
      category: "Action",
      hint: "To give someone greater knowledge and understanding",
    },
    {
      word: "EXISTENCE",
      category: "Concept",
      hint: "The fact or state of living or having objective reality",
    },
    {
      word: "LIBERATION",
      category: "Concept",
      hint: "The act of setting someone free from imprisonment",
    },
    {
      word: "MEDITATION",
      category: "Action",
      hint: "A practice of focus to achieve mental clarity",
    },
    {
      word: "DIMENSION",
      category: "Cosmic",
      hint: "A measurable extent of some kind, like length",
    },
    {
      word: "AWAKENING",
      category: "State",
      hint: "An act of waking from sleep or coming to realize",
    },
    {
      word: "BOUNDLESS",
      category: "Adj",
      hint: "Immense in scope; having no boundaries",
    },
    {
      word: "COSMOLOGY",
      category: "Science",
      hint: "The science of the origin and development of the universe",
    },
    {
      word: "TRANSCEND",
      category: "Action",
      hint: "To rise above or go beyond the limits of",
    },
    {
      word: "VIBRATION",
      category: "Science",
      hint: "An oscillation of the parts of a fluid or elastic solid",
    },
    {
      word: "ULTIMATE",
      category: "Adj",
      hint: "Being or happening at the end of a process",
    },
    {
      word: "DUALITY",
      category: "Philosophy",
      hint: "The quality of being comprised of two parts",
    },
    {
      word: "OMNIPRESENT",
      category: "Adj",
      hint: "Widely or constantly encountered; widespread",
    },
  ],
};

// 4. ECONOMY & REWARDS
export const GAME_STAKES = {
  ONLINE_1V1: {
    ENTRY_FEE: 10,
    BASE_WIN_PRIZE: 20,
    BASE_XP_WIN: 25,
    XP_LOSS: 5,
    STREAK_XP_BONUS: 15,
  },
  CLASSIC: {
    BASE_XP: 15,
    BASE_COINS: 5,
    XP_LOSS_PER_LIFE: 2,
    STREAK_BONUS_MULTIPLIER: 1.5,
  },
  ENDLESS: {
    BASE_XP: 100,
    BASE_COINS: 10,
    HEALTH_BONUS_XP: 10, // XP per remaining life at the end of a word
    HEALTH_BONUS_COINS: 2, // Coins per remaining life
  },
  ENERGY: { MAX_LIVES: 10, RECOVERY_MINUTES: 180 },

  // Logic: Bonus = 100 * Level (Triggered when level changes)
  getArenaUnlockBonus: (level) => 100 * level,
};

// constants.js

export const GAME_CONFIG = {
  MAX_WRONG_GUESSES: 6,
  DAILY_XP_REWARD: 50,
  DAILY_COIN_REWARD: 20,
  DAILY_PERFECT_BONUS: 20,
};
